phrase = "Giraffe Academy"
print ("Giraffe Academy")
print ("Giraffe\nAcademy")
print ("Giraffe\"Academy\"")
print (phrase)
print (phrase.lower() + " is crazy expensive")
print (phrase.upper() + " is crazy expensive")
print (phrase.isupper())
print (phrase.upper().isupper())
print (len(phrase))
print (phrase[0])
print (phrase.index("f"))
print (phrase.index("emy"))
print (phrase.index("affe"))
print (phrase.replace("emy", "atron"))