name = input("enter your name: " )
print (name)
print ((name) + " whats the best pizza place around here?")
age = input(" Enter your age: ")
print ((name) + " whats the best pizza place around here?")
print ("At age " + (age) + " you need little more time to know what your are doing, Ok "+ (name))
