activity = input("User enter favorite activity: ")
game = input("User enter favorite game: ")
plural_appliance = input("User enter appliance: ")
print("Sundays are for " + activity)
print("Chicken excell at " + game)
print(plural_appliance + " are the real stars")
